pipeline {
	agent none
	agent {
		docker{
			image 'maven:3.6.1-jdk-8-slim'
			args '-v $HOME/.m2:/root/.m2'
		}
	}

	stages{
		stage("build") {
			agent {
				docker{
					image 'maven:3.6.1-jdk-8-slim'
					args '-v $HOME/.m2:/root/.m2'
				}
			}
			steps {
				echo 'Compiling worker app'
				dir('worker'){
					sh 'mvn compile'
				}
			}
		}
		stage("test"){
			agent {
				docker{
					image 'maven:3.6.1-jdk-8-slim'
					args '-v $HOME/.m2:/root/.m2'
				}
			}
			steps{
				echo 'Running Unit Tests on worker app'
				dir('worker'){
					sh 'mvn clean test'
				}
			}
		}
		
		stage("package"){
			agent {
				docker{
					image 'maven:3.6.1-jdk-8-slim'
					args '-v $HOME/.m2:/root/.m2'
				}
			}
			steps{
				echo 'Packaging worker app'
				dir('worker'){
					sh 'mvn package -DskipTests'
					archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
				}
			}
		}
		stage('docker-package') {
			agent any
			when{
				changeset '**/worker/**'
			}
			steps{
				echo 'Packagin worker app with docker'
				script{
					docker.withRegistry('https://index.docker.io/v1', '0d547fdc-bc7e-41fd-81f9-1d3c966f8769') {
							def workerImage = docker.build("majakub/worker:v${env.BUILD_ID}", ".worker/")
							workerImage.push()
							workerImage.push("${env.BANCH_NAME}")

					}	
				}
			}
		}
	}

	

	post{
		always{
			echo 'Building multibranch pipeline for worker is completed..'
		}
	}
}
